--batch_size = [512]
--learning_rate = [5]
--ckpt = ["save/SupCon/imagenet100_models/SupCon_new_imagenet100_resnet50_lr_0.5_decay_0.0001_bsz_512_temp_0.1_trial_0_cosine_warm/last.pth",
          "save/SupCon/imagenet100_models/SupCon_old_imagenet100_resnet50_lr_0.5_decay_0.0001_bsz_512_temp_0.1_trial_0_cosine_warm/last.pth"]
--dataset = ["imagenet100"]
